name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install Dependencies
      run: uv sync --frozen
    - name: Run Migrate
      run: uv run python src/manage.py migrate
    - name: Run Django system checks
      run: uv run python src/manage.py check
